### ISSUE TITLE
Too strict in required structure of redis sentinel configs

### ISSUE THREAD

**Issue by xiongchiamiov** [splitio/python-client#150]
Currently, the SDK does some `isinstance()` checking of the configs.  The one I specifically ran into is here: https://github.com/splitio/python-client/blob/71dfab240fd6a88f83b7aed5bbd979597eda01a7/splitio/storage/adapters/redis.py#L377-L379

Generally in Python we'd prefer to use duck typing, rather than specifically checking if something is a tuple (in this case).  The reason for this is that usually we don't actually need a tuple, but just need something that acts like a tuple.  This is exposed in my case because I'm passing in a config block from yaml, and yaml doesn't support tuples with certain unsafe loading operations, and so rather than being a tuple of `(ip, port)`, it's a list of `[ip, port]`.  I _suspect_ this is actually completely fine (since almost anything a tuple supports is also supported by a list), but the code prevents me from doing that.

**Comment by mredolatti** [comment]
Hi @xiongchiamiov, thank you very much for reaching out. We're sorry for any inconveniences caused. Your concern makes total sense, we'll do a little review on our side to see how we can relax some of these constraints while still doing some validation to let the user know as soon as possible if his configuration is not ok.

Is this currently blocking you?

**Comment by xiongchiamiov** [comment]
> Is this currently blocking you?

No, I've just added a little `split_config['redisSentinels'] = [(ip, port) for ip, port in split_config['redisSentinels']]` to remap them, not a big deal (aside from having to do it in each client).

**Comment by mredolatti** [comment]
Hi, we had a couple of discussions with the team, and decided to keep the validations strict, since it provides accurate feedback to the user regarding how the configuration parameters should be passed and helps identifying potential issues with with them. 
In this case, the immutability and simplicity of tuples seems ideal for us when passing port-host pairs. Adapting lists or other iterables, as you point in your example, shouldn't be an issue at all if required.

Thanks and sorry for the delay,
Martin.
