### ISSUE TITLE
Localhost mode fails with empty yaml file

### ISSUE THREAD

**Issue by elhawk** [splitio/python-client#170]
In `_read_splits_from_yaml_file`, if the passed file is empty, `parsed` is `None` and the factory creation fails.

**Comment by chillaq** [comment]
Hi, this is expected behavior since localhost mode must get the Split definitions from the yaml file, if no definitions exist, no treatment can be calculated, I can submit a feature request to log an error message specifying the yaml file is empty.
May I ask why you are creating unit test with empty yaml file? Is it a test when no Splits are defined scenario?

**Comment by chillaq** [comment]
Hi, I am following up on this issue, May I ask why you are creating unit test with empty yaml file? Is it a test when no Splits are defined scenario?

**Comment by chillaq** [comment]
Hi @elhawk , I have not heard back from you in a while, I am closing this issue for now, please let us know if you have any questions, we can reopen it and take it from there.

Thanks
